// Generates src/version.ts from package.json "version".
// Idempotent: only writes when the content actually changes.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");

const pkg = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));
const version = pkg.version;
const target = join(root, "src", "version.ts");

const contents =
  `// AUTO-GENERATED by scripts/gen-version.mjs — do not edit by hand.\n` +
  `export const SDK_VERSION = ${JSON.stringify(version)};\n`;

let existing = "";
try {
  existing = readFileSync(target, "utf8");
} catch {
  // file does not exist yet
}

if (existing === contents) {
  console.log(`gen-version: src/version.ts already up to date (${version})`);
} else {
  writeFileSync(target, contents);
  console.log(`gen-version: wrote src/version.ts (${version})`);
}
